name: Auto Push Updates

on:
  schedule:
    - cron: '0 0 * * *'  # This runs daily at midnight (UTC)
  push:
    branches:
      - main

jobs:
  update-repository:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "USCB_API_KEY=${{ secrets.USCB_API_KEY }}" >> $GITHUB_ENV

      - name: Run your script
        run: |
          python your_script.py  # Your script can now access the API keys via environment variables


      - name: Commit and push changes
        run: |
          git config --global user.name 'your-username'
          git config --global user.email 'your-email@example.com'
          git add .
          git commit -m 'Automated update'
          git push
